Article.create(source: 'New York Times'),
Article.create(source: 'Daily Mail'),
Article.create(source: 'KTVU San Francisco'),
Article.create(source: 'Associated Press'),
Article.create(source: 'YouTube'),
Article.create(source: 'Gizmodo.com'),
Article.create(source: 'The Verge'),
Article.create(source: 'Fox Business'),
Article.create(source: 'Sports Illustrated'),
Article.create(source: 'Ars Technica'),
Article.create(source: 'Engadget'),
Article.create(source: 'Yahoo Entertainment'),
Article.create(source: 'CBS Sports'),
Article.create(source: 'USA Today'),
Article.create(source: 'Daily Beast'),
Article.create(source: 'CNN'),
Article.create(source: 'CNBC'),
Article.create(source: 'The Wall Street Journal'),
Article.create(source: 'Seahawks.com'),
Article.create(source: 'Reuters'),
Article.create(source: 'WMUR Manchester'),
Article.create(source: 'NBC Southern California'),
Article.create(source: 'Fox News'),
Article.create(source: 'KOCO Oklahoma City'),
Article.create(source: 'BuzzFeed News'),
Article.create(source: 'CBS News'),
Article.create(source: 'Eonline.com'),
Article.create(source: 'Entrepreneur'),
Article.create(source: 'Hackaday'),
Article.create(source: 'The Guardian'),
Article.create(source: 'VentureBeat'),
Article.create(source: 'Genieframework.com'),
Article.create(source: 'The Globe And Mail'),
Article.create(source: 'Boing Boing'),
Article.create(source: 'Github.com'),
Article.create(source: 'CNET'),
Article.create(source: 'Slashdot.org'),
Article.create(source: 'Wired'),
Article.create(source: 'The Next Web'),
Article.create(source: 'News@UofT'),
Article.create(source: 'Xataka.com'),
Article.create(source: 'Jl-m.org'),
Article.create(source: 'Substack.com'),
Article.create(source: 'Go350.com'),
Article.create(source: 'Github.io'),
Article.create(source: '9to5Mac'),
Article.create(source: 'E-basteln.de'),